### ISSUE TITLE
Travis CI + Badge

### ISSUE THREAD

**Issue by joehand** [karissa/datpy#10]
I saw there is a Travis CI config but it [doesn't seem to be working](https://travis-ci.org/karissa/datpy). I've never really used Travis CI and couldn't figure out if it was a config error or if it just isn't turned on.

Once it's working, it'd be nice to have a badge and include Python 3 in the tests.

**Comment by karissa** [comment]
OK done!

**Comment by joehand** [comment]
Awesome! Thanks.
