### ISSUE TITLE
Error code 127 from stdout

### ISSUE THREAD

**Issue by joehand** [karissa/datpy#11]
It seems that error code 127 (on [this line](https://github.com/karissa/datpy/blob/master/datpy.py#L202)) catches other errors besides dat not being available.

```
p.returncode = 127
{"error":true,"message":"Error: Must specify dataset (-d)"}
```

I'm a little confused and not quite sure how I got there (since you must specify dataset name when creating it). I'll update if I figure anything else out.

Are the `dat` error codes documented somewhere?

**Comment by joehand** [comment]
Okay, so I was accidentally passing a Pandas series as the `import_dataframe` keys kwarg:

```
dat = Dat()
dat.init()

dataset = Dataset(dat, 'ihazkeys')
df = DataFrame([{'this':'is','a':'dataframe'}])
dataset.import_dataframe(df, keys=df.this)
```

Probably not a smart idea =). But regardless, the error message is not working correctly.

**Comment by karissa** [comment]
Yeah, good question. There are no documented error codes for dat. We should do that :) :) I'll look into that a bit today
