### ISSUE TITLE
Dataframe import/export destroys dtypes

### ISSUE THREAD

**Issue by joehand** [karissa/datpy#12]
When you `import_dataframe` to dat then `export_dataframe` the `dtypes` are lost. This is related to the [schema issue](https://github.com/maxogden/dat/issues/390) discussed yesterday on the call.

If `dat` ends up using datapackage.json its fairly easy to export `DataFrame(s)` to a datapackage file (see [example code here](https://github.com/datasets/nasdaq-listings/blob/master/scripts/process.py#L61)).

**Comment by karissa** [comment]
Ohhh nice! I'm working on the schema stuff now. If you have any ideas on a good CLI interface to specify a schema file to a dataset, I'm all ears. When people import from a dataframe, we can use that interface

**Comment by joehand** [comment]
@karissa is the plan to have one schema per dataset? Or per dat instance? Or whatever the user wants =)?

The datapackage.json spec allows for multiple "datasets" to be in one spec (under the `resources` list). It seems like that'd be good for allowing multiple datasets in one spec. That'd make it easy for when you get several datasets from one source, with a single license & description. But I could also see where you'd want multiple specs in a single dat instance.

RE: the CLI, I'll think on that a bit. If the plan is `1 dataset = 1 schema` then it seems relatively straightforward (`dat -d mydataset --schema=mydataset_schema.json`). If its `1 dat = 1 schema` then [this proposal](https://github.com/maxogden/dat/issues/191) makes sense. If it isn't 1-to-1 it gets a bit more complicated...

**Comment by karissa** [comment]
@joehand yeah, I think one schema per dataset right now is the aim, although in theory a user could probably attach as many as they want to through the `dat write` blob interface.

What if dat spoke datapackage.json? So, if you have one in your dat 'flies' repo (using `dat write`, in 1.0 `dat add`), dat will be able to map those to datasets, as long as the resource 'name' matches the dat dataset name.

**Comment by karissa** [comment]
maybe you could always also just apply references in the `package.json` or as a binary attachment to the dataset.

**Comment by karissa** [comment]
@joehand I updated the repo for dat 1.0 so I'm going to close these PRs
