### ISSUE TITLE
Download - returned value is bugged

### ISSUE THREAD

**Issue by dav009** [karissa/datpy#17]
the return value expects to find : `Downloaded to` in stdout.
this does not seem to be output anymore 
i.e:
```
Downloading Data (3 files, 2 folders, 108.48 kB total)
[Done] examples/kiwi.json
[Done] examples/contracts.csv
[Done] examples/blob.txt
```

**Comment by karissa** [comment]
Sorry, this is fixed in the new version of dat but we haven't published it yet to npm. Give us a few days
