### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by joehand** [karissa/datpy#4]
Would it be possible to support both Python 2 & 3 for this library? I've started a [Python 3 fork](https://github.com/joehand/datpy/tree/python-3) that should support both.

I'll send a PR when it is ready. I wanted to put it in an issue in case anyone else was looking. The fork works for regular usage but doesn't pass all the tests.

Right now the pandas tests are failing in both 2 & 3, everything else passes. I *think* there may be an issue with the `key` storage for dataframes, but I'll open another issue once I figure that out. 

Thanks!

**Comment by palewire** [comment]
+1. Just bumped into this bug myself. If I can help, let me know.

**Comment by joehand** [comment]
@palewire pushed a [new branch](https://github.com/joehand/datpy/tree/python3) that is working on most fronts. Make sure you update to the newest dat CLI on npm (7.0.3) - that was causing me some issues with the keys.

As I said in PR #9 there is still an issue with reading pickle files. I'm not quite sure the best way to handle that, if you have any ideas.

**Comment by palewire** [comment]
Thanks for that. I'm pretty stupid about pickles but if it comes up I'll let you know.

**Comment by karissa** [comment]
This is merged now. As for pickles, I think we should create another function for formatting pickles so users don't have to worry about it
